os:
- osx
- linux
sudo: false
language: node_js
node_js:
- '8.9.0'
- 'stable'
before_install:
- yarn yarn-upgrade
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
script:
- yarn lint
- yarn test
