jobs:
  include:
  - stage: Build for OSX
    language: node_js
    node_js: 8.0.0
    os: osx
    yarn: 1.5.0
    script:
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    - git branch -d release
    - git checkout -b release
    - "yarn darwin"
    after_success:
    - git add -A
    - git commit -am "v1.0.0-${TRAVIS_BUILD_NUMBER}"
    - git push origin release -f
  - stage: Deploy to Github
    deploy:
      provider: releases
      api_key: ${GH_TOKEN}
      file: "./dist/*"
      skip_cleanup: true
      on:
        repo: etaletai13/musicoin-electron
        branches:
          only: release
