#!/usr/bin/env sh

OS=$1

yarn run nativefier -m -n "Musicoin" \
    -a "amd64"  \
    -i "./icon.png" \
    --app-copyright 'Musicoin.org' \
    --app-version 1.0.0 \
    --internal-urls '.*?\.musicoin.org' \
    --width 900 --height 600 \
    --zoom 0.75 \
    --bounce \
    --disable-dev-tools \
    --disable-gpu \
    --honest \
    --single-instance \
    -p ${OS} \
    "Musicoin" \
    "./dist"
